flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: false
    old-locale: false
    network-uri: true
packages:
- '.'
extra-deps: []
# to compile against aeson 0.11.0.0:
# - 'aeson-0.11.0.0'
# - 'fail-4.9.0.0'
# - 'pandoc-types-1.16.1'
resolver: lts-5.8
